### ISSUE TITLE
Pygbe error message when it is execute from terminal Ubuntu 18

### ISSUE THREAD

**Issue by Marr575** [pygbe/pygbe#86]
Pygbe error message when it is execute from terminal Ubuntu 18

Hi again

I have installed pygbe in Ubuntu, when I open anaconda-navigator and run pygbe from the environments it runs perfectly, but when I try to run it from the terminal of Ubuntu without have started anaconda, pygbe sends me this message: 

Traceback (most recent call last):
  File "/usr/local/bin/pygbe", line 11, in <module>
    load_entry_point('PyGBe==0.3.2+5.gea0f875', 'console_scripts', 'pygbe')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/pygbe/main.py", line 20, in <module>
  File "build/bdist.linux-x86_64/egg/pygbe/gmres.py", line 23, in <module>
  File "build/bdist.linux-x86_64/egg/pygbe/matrixfree.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/pygbe/tree/FMMutils.py", line 9, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyGBe-0.3.2+5.gea0f875-py2.7-linux-x86_64.egg/pygbe/tree/multipole.py", line 99
    def multipole_c(K: 'double *', V: 'double *', M: 'double *', Md: 'double *', dxa: 'double *', dya: 'double *', dza: 'double *', index: 'int *', P: 'int', kappa: 'double', Nm: 'int', LorY: 'int') -> "void":
                     ^
SyntaxError: invalid syntax

How I can fix it? I want to run pygbe directly from the terminal 

Regards

**Comment by ncclementi** [comment]
Hello, it looks like it's because you have python 2 by default and pygbe won't run with python 2. You need to make python 3 your default one and that should work. 
I hope this help

**Comment by Marr575** [comment]
Hi, I tried with a symbolic link

sudo ln -s python3.6 /usr/bin/python

or/and adding the alias to the .bashrc

alias python=python3.6

but I still get the same error 
how I can make python 3.6 or the version that need to run pygbe my default python?

**Comment by Marr575** [comment]
I found the solution, it  is necessary to remove pygbe, reinstall python the newest version and at the moment of install pygbe again indicate the newest version of python with python3

$ python3 setup.py install clean

**Comment by ncclementi** [comment]
That seems accurate, since you installed pygbe previous to create the symbolic link. It would make sense to reinstall pygbe after you set python 3 as default.
